INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Jonathan', 'Page', 'solidCamel8', 'Wells Fargo', 126);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Gertrude', 'Hannaford', 'crushedPup2', 'Apple credit_card', 320);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Kyle', 'Smith', 'lazyOatmeal3', 'Citi', 971);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Fannie', 'Johnson', 'worriedGnu2', 'Bank of America', 698);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Guadalupe', 'Scroggs', 'sugaryCow6', 'Bank of America', 928);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('John', 'Best', 'adoringMacaw4', 'Bank of America', 853);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Kristin', 'Hudson', 'needyMallard6', 'Wells Fargo', 753);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Betty', 'Hubbard', 'solemnWildfowl9', 'Chase', 544);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Louis', 'Houston', 'thriftyOatmeal6', 'Bank of America', 762);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Karin', 'Dibbles', 'grumpyPonie2', 'Citi', 10);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Clare', 'Cantey', 'forsakenCoconut5', 'Bank of America', 634);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Pamela', 'Bryant', 'stressedPepper8', 'Chase', 348);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Henry', 'Huber', 'importedPear6', 'American Express', 411);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Richard', 'Adams', 'sadMacaw3', 'Apple credit_card', 845);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Carl', 'Mosteller', 'euphoricCrackers8', 'Discover', 406);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Barbara', 'Mccarty', 'peskyTomatoe5', 'Apple credit_card', 623);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Barbara', 'Pomeroy', 'spiritedShads1', 'American Express', 12);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Guadalupe', 'Shelton', 'excludedGatorade6', 'Apple credit_card', 585);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('Heidi', 'Anderson', 'curiousBoa7', 'Apple credit_card', 607);
INSERT INTO users (first_name, last_name, username, credit_card, balance) VALUES ('James', 'Meder', 'dreadfulPoultry0', 'Chase', 770);



INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'Curry up Now', 6, 'Text me', 26, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Cava', 5, 'Text me', 69, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Cava', 0, 'Gate code is 1234', 77, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Cava', 6, 'Text me', 75, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'ACM Pizza', 1, 'Leave at back door', 55, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'ACM Pizza', 6, 'Gate code is 1234', 95, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Curry up Now', 2, 'Ring doorbell', 67, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Cheese Pizza', 'Tapioca Express', 4, 'Leave at front door', 81, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'The Melt', 1, 'Ring doorbell', 79, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Mendocino Farms', 4, 'Leave at front door', 20, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'The Melt', 6, 'Ring doorbell', 25, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'BJs', 3, 'Leave at front door', 48, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'The Melt', 6, 'Leave at front door', 63, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'Chipotle', 2, 'Text me', 48, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Mendocino Farms', 3, 'Ring doorbell', 27, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'Curry up Now', 6, 'Leave at front door', 96, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'BJs', 5, 'Ring doorbell', 58, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'Nobu Malibu', 0, 'Leave at back door', 74, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Panda Express', 5, 'Gate code is 1234', 16, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'BJs', 1, 'Text me', 49, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'Cava', 1, 'Text me', 9, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'The Melt', 2, 'Text me', 11, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Tapioca Express', 0, 'Text me', 30, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'Chipotle', 0, 'Gate code is 1234', 1, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Chipotle', 0, 'Leave at front door', 64, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'BJs', 3, 'Leave at front door', 84, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'The Melt', 1, 'Ring doorbell', 62, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Chipotle', 1, 'Leave at front door', 100, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Caviar', 'Chipotle', 5, 'Leave at front door', 42, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Nobu Malibu', 2, 'Leave at back door', 67, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Caviar', 'BJs', 1, 'Leave at front door', 70, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Nobu Malibu', 0, 'Ring doorbell', 56, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Nobu Malibu', 6, 'Ring doorbell', 58, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Cheese Pizza', 'Panda Express', 1, 'Leave at back door', 51, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'ACM Pizza', 4, 'Leave at back door', 56, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Chipotle', 1, 'Leave at back door', 97, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Tapioca Express', 3, 'Ring doorbell', 14, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Cava', 1, 'Leave at front door', 31, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'Tapioca Express', 2, 'Leave at front door', 36, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Panda Express', 4, 'Gate code is 1234', 89, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'The Melt', 0, 'Gate code is 1234', 26, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Chipotle', 3, 'Gate code is 1234', 64, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'BJs', 3, 'Leave at front door', 93, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Caviar', 'Chipotle', 5, 'Leave at front door', 98, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'The Melt', 2, 'Gate code is 1234', 68, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'BJs', 5, 'Leave at back door', 60, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Mendocino Farms', 2, 'Leave at back door', 1, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'BJs', 2, 'Leave at back door', 60, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'The Melt', 2, 'Gate code is 1234', 12, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Curry up Now', 2, 'Leave at front door', 13, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'Tapioca Express', 4, 'Text me', 14, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Panda Express', 1, 'Gate code is 1234', 61, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Nobu Malibu', 6, 'Ring doorbell', 66, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'The Melt', 5, 'Text me', 6, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Tapioca Express', 6, 'Gate code is 1234', 7, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Curry up Now', 4, 'Text me', 41, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'The Melt', 5, 'Leave at front door', 18, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Chipotle', 3, 'Ring doorbell', 0, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'The Melt', 3, 'Text me', 99, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'Nobu Malibu', 0, 'Leave at back door', 46, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'ACM Pizza', 3, 'Leave at front door', 64, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'Cava', 3, 'Ring doorbell', 31, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Nobu Malibu', 2, 'Text me', 77, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'Chipotle', 2, 'Text me', 64, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'Panda Express', 2, 'Leave at back door', 6, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Caviar', 'Mendocino Farms', 0, 'Ring doorbell', 86, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Mendocino Farms', 2, 'Leave at back door', 22, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Panda Express', 2, 'Gate code is 1234', 32, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'ACM Pizza', 0, 'Leave at front door', 40, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Caviar', 'Chipotle', 1, 'Ring doorbell', 76, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Panda Express', 2, 'Text me', 45, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'The Melt', 0, 'Ring doorbell', 38, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'The Melt', 1, 'Leave at back door', 76, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Cheese Pizza', 'The Melt', 4, 'Leave at back door', 3, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'ACM Pizza', 5, 'Leave at back door', 54, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'Curry up Now', 3, 'Leave at front door', 82, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Curry up Now', 5, 'Gate code is 1234', 40, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Panda Express', 6, 'Leave at back door', 91, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Mendocino Farms', 5, 'Ring doorbell', 41, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'The Melt', 2, 'Leave at back door', 93, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Falafels', 'The Melt', 6, 'Text me', 94, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Boba', 'Tapioca Express', 6, 'Leave at front door', 97, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'Chipotle', 5, 'Leave at front door', 62, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Tapioca Express', 6, 'Ring doorbell', 73, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Cava', 6, 'Ring doorbell', 51, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'Panda Express', 6, 'Leave at back door', 4, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Orange Chicken', 'Mendocino Farms', 0, 'Leave at back door', 6, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Curry up Now', 1, 'Ring doorbell', 67, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Nobu Malibu', 0, 'Gate code is 1234', 35, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Tapioca Express', 6, 'Leave at front door', 99, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'Mendocino Farms', 4, 'Leave at front door', 42, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Cheese Pizza', 'BJs', 1, 'Ring doorbell', 80, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Paneer Tikka Masala', 'BJs', 1, 'Leave at back door', 65, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'The Melt', 2, 'Leave at front door', 27, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'The Melt', 4, 'Text me', 41, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'Curry up Now', 2, 'Gate code is 1234', 74, 'Placed');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Chicken Burrito', 'Nobu Malibu', 4, 'Leave at back door', 88, 'Delivered');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Caviar', 'Nobu Malibu', 5, 'Leave at back door', 39, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Mozzarella Sandwich', 'Chipotle', 4, 'Leave at back door', 88, 'Cancelled');
INSERT INTO orders (order_name, restaurant, quantity, instructions, cost, order_status) VALUES ('Grilled Cheese Sandwich', 'Tapioca Express', 0, 'Leave at front door', 9, 'Placed');
